[project]
name = "airflow-luciano"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=2.10.5",
    "db>=0.1.1",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
]
